// front/react/src/components/TaskList/TaskList.js
import React from "react";
import Task from "../Task/Task";
import "./TaskList.css";

function TaskList({ tasksList, updateTasksHandler }) {
  return (
    <>
      <section className="tasks-section">
        {tasksList.length > 0 ? (
          tasksList.map((el) => (
            <Task
              key={el.id}
              title={el.title}
              description={el.description}
              id={el.id}
              creationTime={el.creationTime}
              completed={el.completed}
              updateTasksHandler={updateTasksHandler}
            />
          ))
        ) : (
          <p className="no-list">NO TASKS</p>
        )}
      </section>
    </>
  );
}

export default TaskList;

// front/vue/src/components/TaskList.vue
<script>
import { defineComponent } from 'vue'
import Task from './Task.vue'

const TaskList = defineComponent({
  props: {
    tasks: Array,
    getAllTasks: Function
  },
  data() {
    return {
      tasksList: []
    }
  },
  components: {
    Task
  },
  watch: {
    tasks(newTasks) {
      this.tasksList = newTasks
    }
  }
})

export default TaskList
</script>

<template>
  <section class="tasks-section" v-if="tasksList.length > 0">
    <Task
      v-for="item in tasksList"
      :key="item.id"
      :title="item.title"
      :description="item.description"
      :completed="item.completed"
      :creationTime="item.creationTime"
      :getAllTasks="getAllTasks"
    />
  </section>
  <section v-else class="tasks-section">
    <p v-if="!tasks.length || tasks.length <= 0" class="no-list">NO TASKS</p>
  </section>
</template>

<style scoped>
.no-list {
  color: gray;
  font-weight: 600;
  text-transform: uppercase;
  font-size: 16px;
}

.tasks-section {
  width: 100%;
  display: flex;
  flex-direction: column;
  align-items: center;
}
</style>
